package drools.rule.alarm;

import com.pachiraframework.watchdog.event.event.MetricReportEvent;
import com.pachiraframework.watchdog.action.ConsoleAction;
import com.pachiraframework.watchdog.action.SmsAction;
import com.pachiraframework.watchdog.action.EmailAction;

global com.pachiraframework.watchdog.util.SpringContext spring;
dfd
rule "控制台打印监控明细-测试阶段使用"
	no-loop true
	salience 1 //数字越大，优先级越高
	date-expires   "20.3.2018 16:00"
	when 
		$event:MetricReportEvent(monitor.type=='PING')
	then
		spring.get(ConsoleAction.class).execute($event);
end 

rule "非工作时间短信发送监控信息"
	no-loop true
	salience 100 //数字越大，优先级越高
	calendars "not-weekdays"
	when 
		$event:MetricReportEvent(monitor.type=='PING')
	then
		spring.get(SmsAction.class).execute($event);
end 

rule "邮件记录所有监控信息"
	no-loop true
	salience 10 //数字越大，优先级越高
	when 
		$event:MetricReportEvent(monitor.type=='PING')
	then
		spring.get(EmailAction.class).execute($event);
end 