
####################################################################################################
####                                             监控器信息                                                                                                                                          #####
####################################################################################################
ID:${monitor.id}		
类型:${monitor.type}		
名称:${monitor.name}	
主机:${monitor.host}
端口:${monitor.port}
调度器:${monitor.schedulerId}
####################################################################################################
####                                             监控记录                                                                                                                                              #####
####################################################################################################
ID:${record.id}
进程ID:${record.pid!""}
服务器已运行秒数:${record.uptime!""}
服务器当前Unix时间戳:${record.time!""}
memcache版本:${record.version!""}
libevent:${record.libevent!""}
操作系统指针大小:${record.pointerSize!""}
进程累计用户时间:${record.rusageUser!""}
进程累计系统时间:${record.rusageSystem!""}
当前连接数量:${record.currConnections!""}
Memcached运行以来连接总数:${record.totalConnections!""}
Memcached分配的连接结构数量:${record.connectionStructures!""}
reservedFds:${record.reservedFds!""}
get命令请求次数:${record.cmdGet!""}
set命令请求次数:${record.cmdSet!""}
flush命令请求次数:${record.cmdFlush!""}
cmdTouch:${record.cmdTouch!""}
get命令命中次数:${record.getHits!""}
get命令未命中次数:${record.getMisses!""}
delete命令未命中次数:${record.deleteMisses!""}
delete命令命中次数:${record.deleteHits!""}
incr命令未命中次数:${record.incrMisses!""}
incr命令命中次数:${record.incrHits!""}
decr命令未命中次数:${record.decrMisses!""}
decr命令命中次数:${record.decrHits!""}
cas命令未命中次数:${record.casMisses!""}
cas命令命中次数:${record.casHits!""}
使用擦拭次数:${record.casBadval!""}
touchHits:${record.touchHits!""}
touchMisses:${record.touchMisses!""}
认证命令处理的次数:${record.authCmds!""}
认证失败数目:${record.authErrors!""}
读取总字节数:${record.bytesRead!""}
发送总字节数:${record.bytesWritten!""}
分配的内存总大小（字节）:${record.limitMaxbytes!""}
服务器是否达到过最大连接（0/1）:${record.acceptingConns!""}
失效的监听数:${record.listenDisabledNum!""}
当前线程数:${record.threads!""}
连接操作主动放弃数目:${record.connYields!""}
hashPowerLevel:${record.hashPowerLevel!""}
hashBytes:${record.hashBytes!""}
hashIsExpanding:${record.hashIsExpanding!""}
expiredUnfetched:${record.expiredUnfetched!""}
evictedUnfetched:${record.evictedUnfetched!""}
当前存储占用的字节数:${record.bytes!""}
当前存储的数据总数:${record.currItems!""}
启动以来存储的数据总数:${record.totalItems!""}
LRU释放的对象数目:${record.evictions!""}
已过期的数据条目来存储新数据的数目:${record.reclaimed!""}
消息:${record.message!""}
<#include "/alarm/common/console_reports.ftl">
